name: intake_customer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_screenutil: 5.3.0
  http: 0.13.4
  get_storage: 2.0.3
  intl_phone_number_input: ^0.7.0+2
  fluttertoast: ^8.0.8
  intl: 0.17.0
  flutter_osm_plugin: 0.31.0
  cached_network_image: 3.2.0
  shimmer: 2.0.0
  image_picker: ^0.8.4+10
  lottie: 1.2.2
  flutter_svg: 1.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/
    - assets/images/
    - assets/icons/
    - assets/lottie/
  uses-material-design: true

