name: intake_customer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_screenutil: 5.3.0
  http: 0.13.4
  get_storage: 2.0.3
  intl_phone_number_input: ^0.7.0+2
  fluttertoast: ^8.0.8
  intl: 0.17.0
  flutter_osm_plugin: 0.31.0
  cached_network_image: 3.2.0
  shimmer: 2.0.0
  image_picker: ^0.8.4+10
  lottie: 1.2.2
  location: ^4.2.0
  flutter_svg: ^0.22.0
  flutter:
    sdk: flutter
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.11
  url_launcher: ^6.0.20
  flutter_html: ^2.2.1
  flutter_spinkit: ^5.1.0
  flutter_local_notifications: ^9.4.0
  webview_flutter: ^2.8.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

  flutter_native_splash: ^2.1.3+1
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  image: assets/logo/logo-name.png
  color: '#ffffff'

flutter_icons:
  image_path: "assets/logo/logo-launcher.png"
  android: true
  ios: true

flutter: 
  assets: 
    - assets/logo/
    - assets/images/
    - assets/icons/
    - assets/lottie/
  uses-material-design: true

